# Generated by Django 5.2.4 on 2025-07-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_remove_listeninghistory_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
