# Generated by Django 5.2.4 on 2025-07-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_track_playlist_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeninghistory',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='song_title',
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_records', to='mypage.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='track_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
